# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bob-friend-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bob-friend-iOS
  
  pod 'Alamofire', '~> 5.1'

  target 'bob-friend-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bob-friend-iOSUITests' do
    # Pods for testing
  end

end
